"""Edited User Model

Revision ID: 2308dfad5547
Revises: 4613e71609e8
Create Date: 2025-11-17 10:26:08.034758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2308dfad5547'
down_revision: Union[str, Sequence[str], None] = '4613e71609e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
