"""made model for other auth

Revision ID: 581b31edc5c0
Revises: db3b83ea8625
Create Date: 2025-12-18 18:18:56.569445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581b31edc5c0'
down_revision: Union[str, Sequence[str], None] = 'db3b83ea8625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('social_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'social_id', name='uq_provider_social_id')
    )
    op.create_index(op.f('ix_social_accounts_social_id'), 'social_accounts', ['social_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_accounts_social_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
