"""empty message

Revision ID: a734ffd07d0f
Revises: dd847384719e
Create Date: 2025-12-19 18:55:30.484943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a734ffd07d0f'
down_revision: Union[str, Sequence[str], None] = 'dd847384719e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'social_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_accounts', type_='foreignkey')
    op.drop_column('social_accounts', 'user_id')
    # ### end Alembic commands ###
