"""Add cascade delete

Revision ID: db3b83ea8625
Revises: 2308dfad5547
Create Date: 2025-12-06 22:54:05.415335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3b83ea8625'
down_revision: Union[str, Sequence[str], None] = '2308dfad5547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_user_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('workoutdata_user_id_fkey'), 'workoutdata', type_='foreignkey')
    op.drop_constraint(op.f('workoutdata_category_id_fkey'), 'workoutdata', type_='foreignkey')
    op.create_foreign_key(None, 'workoutdata', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workoutdata', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workoutdata', type_='foreignkey')
    op.drop_constraint(None, 'workoutdata', type_='foreignkey')
    op.create_foreign_key(op.f('workoutdata_category_id_fkey'), 'workoutdata', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('workoutdata_user_id_fkey'), 'workoutdata', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_user_id_fkey'), 'categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
